## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

env:
  global:
    - PYTHON=""

after_success:
  # push coverage results to Coveralls
  - julia -e 'VERSION >= v"0.7.0-DEV.5183" && import Pkg; cd(Pkg.dir("TauPy")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
